header:

  license:
    spdx-id: 'MPL-2.0'
    copyright-owner: 'Gabriel Feo'
    content: |
      Copyright (c) 2022 Gabriel Feo
      
      This Source Code Form is subject to the terms of the Mozilla Public
      License, v. 2.0. If a copy of the MPL was not distributed with this
      file, You can obtain one at https://mozilla.org/MPL/2.0/.
    pattern: 'Copyright \(c\) 2022 Gabriel Feo.*Mozilla Public\n?License.*https'

  paths:
    - '**'

  paths-ignore:
    - 'LICENSE'
    - 'README.md'
    - '.gitignore'
    - '.licenserc.yaml'
    - '**/*.properties'
    - '**/*.md'
    - '**/*.jar'
    - '**/*.json'
    - 'gradlew'
    - 'gradlew.bat'

  comment: never
