name: CLI release

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:

  package-linux-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package release
        uses: ./.github/actions/package-cli-release
        with:
          artifact-name: linux
          tasks: :cli:packageReleaseLinuxX64
      - name: Parse version number
        run: |
          VERSION="$(ls ./cli/build/release/*.zip | head -1 | grep -Eo 'v[0-9.]+')"
          echo "Parsed version $VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

  package-macos-release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package release
        uses: ./.github/actions/package-cli-release
        with:
          artifact-name: macos
          tasks: :cli:packageReleaseMacosX64

  create-release:
    needs: [package-linux-release, package-macos-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_USERNAME: 'gabrielfeo'
      GITHUB_TOKEN: ${{ secrets.CROSS_REPO_GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.0
        with:
          path: artifacts/
      - name: Create GitHub release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ needs.package-linux-release.outputs.version }}
          target_commitish: ${{ github.sha }}
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            artifacts/linux/*
            artifacts/macos/*
      - name: Update Homebrew formula
        run: |
          .github/steps/update-homebrew-formula.py \
            --version "${{ needs.package-linux-release.outputs.version }}" \
            --trigger-source "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --assets artifacts/linux/* artifacts/macos/*
