name: CLI release

on:
  push:
    branches: [feature/cli-release]
    tags: [v*]

jobs:

  build-linux-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build release
        uses: ./.github/actions/build-cli-release
        with:
          artifact-name: linux
          tasks: :cli:packageReleaseLinuxX64

  build-macos-release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build release
        uses: ./.github/actions/build-cli-release
        with:
          artifact-name: macos
          tasks: :cli:packageReleaseMacosX64

  create-release:
    needs: [build-linux-release, build-macos-release]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.0
        with:
          path: release/
      - run: ls -R
