name: CLI release

on:
  push:
    branches: [main]

jobs:

  package-linux-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package release
        uses: ./.github/actions/package-cli-release
        with:
          artifact-name: linux
          tasks: :cli:packageReleaseLinuxX64

  package-macos-release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package release
        uses: ./.github/actions/package-cli-release
        with:
          artifact-name: macos
          tasks: :cli:packageReleaseMacosX64

  create-release:
    needs: [package-linux-release, package-macos-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3.0.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.0
        with:
          path: artifacts/
      - name: Restore conventional directory structure
        run: |
          mkdir -p ./cli/build/release
          find artifacts -type f -exec mv {} ./cli/build/release/ \;
      - name: Parse version number
        id: parse-version
        run: |
          version="$(ls ./cli/build/release/*.zip | head -1 | grep -Eo 'v[0-9.]+')"
          echo "Parsed version $version" 
          echo "::set-output name=version::$(echo $version)"
      - name: Create GitHub release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ steps.parse-version.outputs.version }}
          target_commitish: ${{ github.sha }}
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: cli/build/release/*
      - name: Trigger Homebrew formula update
        run: |
          .github/workflows/trigger_homebrew_formula_update.py \
            --version "${{ steps.parse-version.outputs.version }}" \
            --trigger-source "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --username "gabrielfeo" \
            --password "${{ github.token }}"
