# Copyright (c) 2022 Gabriel Feo
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.        

name: 'CLI release'

on:
  push:
    tags: [v*]

defaults:
  run:
    shell: bash

jobs:

  parse-tag:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.ref_name }}
    outputs:
      name: ${{ env.TAG_NAME }}
      subject: ${{ env.TAG_SUBJECT }}
      body: ${{ env.TAG_BODY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse tag info
        run: ./.github/steps/parse-tag-info.sh "${{ env.TAG_NAME }}" >> "$GITHUB_ENV"

  package-linux-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package release
        uses: ./.github/actions/build
        with:
          artifact-name: 'linux'
          tasks: ':cli:packageReleaseLinuxX64'
          path-to-upload: 'cli/build/release/**'

  package-macos-release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package release
        uses: ./.github/actions/build
        with:
          artifact-name: 'macos'
          tasks: ':cli:packageReleaseMacosX64'
          path-to-upload: 'cli/build/release/**'

  create-release:
    needs: [parse-tag, package-linux-release, package-macos-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_USERNAME: 'gabrielfeo'
      GITHUB_TOKEN: ${{ secrets.CROSS_REPO_GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.0
        with:
          path: 'artifacts/'
      - name: Create GitHub release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ needs.parse-tag.outputs.name }}
          target_commitish: ${{ github.sha }}
          draft: true
          body: |
            ${{ needs.parse-tag.outputs.subject }}

            ${{ needs.parse-tag.outputs.body }}
          fail_on_unmatched_files: true
          files: |
            artifacts/linux/*
            artifacts/macos/*
      - name: Update Homebrew formula
        run: |
          .github/steps/update-homebrew-formula.py \
            --version "${{ needs.parse-tag.outputs.name }}" \
            --trigger-source "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --assets artifacts/linux/* artifacts/macos/*
