# Copyright (c) 2022 Gabriel Feo
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.        

name: 'CLI release'

on:
  push:
    tags: ['*/v*']

defaults:
  run:
    shell: bash

jobs:

  package-linux-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Package release
        uses: ./.github/actions/build
        with:
          artifact-name: 'linux'
          tasks: ':cli:packageReleaseLinuxX64'
          path-to-upload: 'cli/build/release/**'

  package-macos-release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Package release
        uses: ./.github/actions/build
        with:
          artifact-name: 'macos'
          tasks: ':cli:packageReleaseMacosX64'
          path-to-upload: 'cli/build/release/**'

  create-release:
    needs: [package-linux-release, package-macos-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_USERNAME: 'gabrielfeo'
      GITHUB_TOKEN: ${{ secrets.CROSS_REPO_GITHUB_TOKEN }}
      TAG_NAME: ${{ github.ref_name }}
      ACTION_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch actual tag
        run: .github/steps/fetch-actual-tag.sh "$TAG_NAME"
      - name: Require annotated tag
        run: .github/steps/require-annotated-tag.sh "$TAG_NAME"
      - name: Parse tag version
        run: .github/steps/parse-tag-version.sh "$TAG_NAME" | tee -a "$GITHUB_ENV"
      - name: Parse tag message
        run: ./.github/steps/parse-tag-message.sh "$TAG_NAME" | tee ./tag_message
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.0
        with:
          path: 'artifacts/'
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          target_commitish: ${{ github.sha }}
          draft: true
          body_path: ./tag_message
          fail_on_unmatched_files: true
          files: |
            artifacts/linux/*
            artifacts/macos/*
      - name: Update Homebrew formula
        run: |
          .github/steps/update-homebrew-formula.py \
            --version "$TAG_VERSION" \
            --trigger-source "$ACTION_RUN_URL" \
            --assets artifacts/linux/* artifacts/macos/*
