name: 'Verify PR'

on:
  pull_request

jobs:
  check-license-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run license-eye
        uses: apache/skywalking-eyes@v0.2.0
