# Copyright (c) 2022 Gabriel Feo
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.        

name: 'Verify PR'

on:
  pull_request

jobs:

  check-license-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run license-eye
        uses: apache/skywalking-eyes@v0.2.0

  check-build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run 'check' tasks
        uses: ./.github/actions/build
        with:
          tasks: 'check'

  check-shell-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get changed files
        id: diff
        uses: tj-actions/changed-files@v18.6
        with:
          files: '**/*.sh'
      - name: shellcheck
        if: ${{ steps.diff.outputs.any_modified }}
        uses: docker://koalaman/shellcheck:latest
        with:
          args: ${{ steps.diff.outputs.all_modified_files }}
